services:
  dc-check-server:
    container_name: dc-check-server
    hostname: check-server
    image: ghcr.io/svenfinn/dc-check-server
    restart: unless-stopped
    networks:
      - displaycontroller
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - local-db=../database/local
        - screen-manager=../screens/screenManager/types
        - logger=../logger
      args:
        - MIN_MEYTON_VERSION=${MIN_MEYTON_VERSION}
        - MAX_MEYTON_VERSION=${MAX_MEYTON_VERSION}
        - MEYTON_SSH_USER=${MEYTON_SSH_USER}
        - MEYTON_SSH_PASS=${MEYTON_SSH_PASS}
        - SELF_DB_URL=${SELF_DB_URL}
    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully
      dc-rabbitmq:
        condition: service_healthy
