services:
  dc-portainer:
    image: portainer/portainer-ce:latest
    container_name: dc-portainer
    hostname: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - displaycontroller

volumes:
  dc_portainer_data:
